sonar.projectKey=oficina-mecanica
sonar.projectName=Oficina Mecânica API
sonar.projectVersion=1.0

sonar.sources=.
sonar.language=py

sonar.exclusions=**/migrations/**,**/fixtures/**,ruvector.db,pentest.py,staticfiles/**,**/__pycache__/**

sonar.python.coverage.reportPaths=coverage.xml

sonar.host.url=http://localhost:9000
# Token lido via variável de ambiente SONAR_TOKEN ou passado na linha de comando:
# sonar-scanner -Dsonar.token=$env:SONAR_TOKEN  (PowerShell)
# sonar-scanner -Dsonar.token=$SONAR_TOKEN       (bash)
