apiVersion: v1
kind: Secret
metadata:
  name: oficina-secret
  namespace: oficina
type: Opaque
stringData:
  SECRET_KEY: "CHANGE_ME_SECRET_KEY"
  POSTGRES_DB: "oficina"
  POSTGRES_USER: "oficina_user"
  POSTGRES_PASSWORD: "CHANGE_ME_DB_PASSWORD"
