# Generated by Django 5.1.15 on 2026-04-04 02:38

import atendimento.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=14, unique=True, validators=[atendimento.models.validate_documento])),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_atual', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor_mao_de_obra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RECEBIDA', 'Recebida'), ('DIAGNOSTICO', 'Em diagnóstico'), ('AGUARDANDO', 'Aguardando aprovação'), ('EXECUCAO', 'Em execução'), ('FINALIZADA', 'Finalizada'), ('ENTREGUE', 'Entregue')], default='RECEBIDA', max_length=20)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimento.cliente')),
                ('servicos', models.ManyToManyField(blank=True, to='atendimento.servico')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPecaOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pecas', to='atendimento.ordemservico')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimento.peca')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True, validators=[atendimento.models.validate_placa])),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.PositiveIntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='atendimento.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimento.veiculo'),
        ),
    ]
