# Generated by Django 5.1.15 on 2026-04-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_finalizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_inicio_execucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
