# Generated by Django 5.1.15 on 2026-05-01 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0003_cliente_created_by_itempecaos_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itempecaos',
            name='quantidade_utilizada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ItemServicoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_servico_criados', to=settings.AUTH_USER_MODEL)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_servico', to='atendimento.ordemservico')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_servico', to='atendimento.servico')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoItemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('item_peca_os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='atendimento.itempecaos')),
                ('item_servico_os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='atendimento.itemservicoos')),
            ],
        ),
        # Django cannot ALTER a plain M2M field to a through-model M2M.
        # The solution: drop the old junction table, then update only Django's
        # internal state to point servicos -> ItemServicoOS (already created above).
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS atendimento_ordemservico_servicos;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='ordemservico',
                    name='servicos',
                    field=models.ManyToManyField(blank=True, through='atendimento.ItemServicoOS', to='atendimento.servico'),
                ),
            ],
        ),
    ]
