# Generated by Django 5.1.15 on 2026-05-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0004_itempecaos_quantidade_utilizada_itemservicoos_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumoitemservico',
            unique_together={('item_servico_os', 'item_peca_os')},
        ),
        migrations.AlterUniqueTogether(
            name='itemservicoos',
            unique_together={('ordem_servico', 'servico')},
        ),
    ]
