# Generated by Django 5.1.15 on 2026-05-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0005_alter_consumoitemservico_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('RECEBIDA', 'Recebida'), ('DIAGNOSTICO', 'Em diagnóstico'), ('AGUARDANDO', 'Aguardando aprovação'), ('EXECUCAO', 'Em execução'), ('FINALIZADA', 'Finalizada'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], default='RECEBIDA', max_length=20),
        ),
    ]
