# Generated by Django 5.1.15 on 2026-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0006_add_status_cancelada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Clientes inativos não podem fazer login'),
        ),
    ]
