# Generated by Django 5.1.15 on 2026-09-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atendimento", "0007_add_data_ultima_transicao"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="ativo",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
